apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-db-data-pietanze
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-db-data-menu
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-db-data-ordini
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
